query projectList {
  projectList {
    id
    rev
    title
    people {
      proposers {
        id
        realName
        userName
      }
      leaders {
        id
        realName
        userName
      }
      involved {
        id
        realName
        userName
      }
    }
    description
    category {
      name
    }
    flags
  }
}
